version: '3'
services:
  meuprimeirocrudgo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=mongodb://localhost:27017
      - DB_NAME=mongodb
      - DB_USER_COLLECTION=users
      - DB_POST_COLLECTION=posts
      - DB_CATEGORY_COLLECTION=categories
      - JWT_SECRET_KEY=jwt_secret
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - meu_crud_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - meu_crud_network

networks:
  meu_crud_network: